# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
<!DOCTYPE html>: This declaration specifies the HTML version.

<html>: This tag represents the root element of an HTML page.

<head>: This tag contains meta

information about the HTML document. <meta charset="UTF-8">: This tag specifies the character encoding for the HTML document.

<meta name="viewport" content="width =device-width, initial-scale=1.0">: This tag sets the viewport properties for responsive web design.

<link rel="pingback" href="https:// toonworld4all.me/xmlrpc.php">: This tag specifies the URL for the pingback file.

<link rel="profile" href="https://gmpg.org /xfn/11">: This tag specifies the URL for the profile file.

- <title>: This tag sets the title of the HTML document.

<meta name="robots" content="max-image-preview:large">This tag sets the indexing and crawling instructions for search engines.

<meta name="google-site-verification" content="V75US_6ftmWwQajGGdjle_Hwv lyGsudtTJ6bXUWSSjQ">: This tag verifies the ownership of the website for Google Search Console.

<link rel="canonical" href="https:// toonworld4all.me/">: This tag specifies the canonical URL for the page.

<meta name="generator" content="All in One SEO (AIOSEO) 4.4.8">: This tag indicates the generator or software used to create the HTML document.

<meta property="og:locale" content="en_US">: This tag sets the Open Graph locale for Facebook.

<meta property="og:site_name" content="Toon World4All">: This tag specifies the site name for Open Graph.

<meta property="og:type" content="website">: This tag sets the Open Graph type for the website.

<meta property="og:title" content="Toon World Home | Toon World4All">: This tag sets the title for Open Graph.

- <meta property="og:url" content="https://toonworld4all.me/">: This tag sets the URL for Open Graph.

<meta name="twitter:card" content="summary_large_image">: This tag specifies the card type for Twitter. <meta name
